### ISSUE TITLE
first-init process, does not find the letscoordinate/letsco-front:latest image

### ISSUE THREAD

**Issue by joyshmitz** [opfab/letscoordinate#73]
by executing the command `./server.sh -f start` first-init process, does not find the `letscoordinate/letsco-front:latest` image however there is a `letscoordinate/frontend` image in the repository which seems to fit the purpose.

maybe I need to change the name of the image to the `letscoordinate/frontend` in docker-compose.yml?

by changing the name, the frontend service started working and initialization went without errors,

**Comment by woueslati** [comment]
Hello, in next releases the docker images' names will be `letscoordinate/backend` for letsco-api module and `letscoordinate/frontend` for letsco-front module. It is fixed in the snapshot version `1.3.1.SNAPSHOT` and will be officially delivered in the release `1.3.1.RELEASE` (first half of october)
